#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.components.dataproxy }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "inlong.fullname" . }}-{{ .Values.dataproxy.component }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inlong.commonLabels" . | nindent 4 }}
    component: {{ .Values.dataproxy.component }}
spec:
  serviceName: {{ template "inlong.fullname" . }}-{{ .Values.dataproxy.component }}
  replicas: {{ .Values.dataproxy.replicas }}
  selector:
    matchLabels:
      {{- include "inlong.matchLabels" . | nindent 6 }}
      component: {{ .Values.dataproxy.component }}
  updateStrategy:
    type: {{ .Values.dataproxy.updateStrategy.type | quote }}
  podManagementPolicy: {{ .Values.dataproxy.podManagementPolicy | quote }}
  template:
    metadata:
      labels:
        {{- include "inlong.template.labels" . | nindent 8 }}
        component: {{ .Values.dataproxy.component }}
      {{- if .Values.dataproxy.annotations }}
      annotations:
        {{- toYaml .Values.dataproxy.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.dataproxy.tolerations }}
      tolerations:
        {{- toYaml .Values.dataproxy.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.dataproxy.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.dataproxy.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.dataproxy.affinity }}
      affinity:
        {{- toYaml .Values.dataproxy.affinity | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.dataproxy.terminationGracePeriodSeconds }}
      initContainers:
        - name: wait-{{ .Values.manager.component }}-ready
          image: {{ .Values.images.initContainer.repository }}:{{ .Values.images.initContainer.tag }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              count={{ .Values.manager.replicas }}
              for i in $(seq 0 $(expr $count - 1))
              do
                replica="{{ template "inlong.fullname" . }}-{{ .Values.manager.component }}-$i"
                host="$replica.{{ template "inlong.manager.hostname" . }}"
                port={{ .Values.manager.port }}
                until nc -z $host $port 2>/dev/null
                do
                  echo "waiting for $replica to be ready"
                  sleep 3
                done
              done
      containers:
        - name: {{ template "inlong.fullname" . }}-{{ .Values.dataproxy.component }}
          image: {{ .Values.images.dataproxy.repository }}:{{ .Values.images.dataproxy.tag }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          {{- if .Values.dataproxy.resources }}
          resources:
            {{- toYaml .Values.dataproxy.resources | nindent 12 }}
          {{- end }}
          env:
            - name: MANAGER_OPENAPI_IP
              value: {{ include "inlong.manager.hostname" . | quote }}
            - name: MANAGER_OPENAPI_PORT
              value: {{ .Values.manager.port | quote }}
            - name: AUDIT_PROXY_URL
              value: "{{ template "inlong.audit.hostname" . }}:{{ .Values.audit.port }}"
            {{- range $key, $value := .Values.dataproxy.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: TZ
              value: {{ .Values.timezone }}
          ports:
            - name: {{ .Values.dataproxy.component }}-port
              containerPort: 46801
          livenessProbe:
            tcpSocket:
              port: {{ .Values.dataproxy.component }}-port
            initialDelaySeconds: 10
            failureThreshold: 2
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
          - name: {{ template "inlong.fullname" . }}-{{ .Values.dataproxy.component }}-{{ .Values.dataproxy.volumes.name }}
            mountPath: /opt/inlong-dataproxy/data
      volumes:
      {{- if not .Values.dataproxy.volumes.persistence }}
      - name: {{ template "inlong.fullname" . }}-{{ .Values.dataproxy.component }}-{{ .Values.dataproxy.volumes.name }}
        emptyDir: {}
      {{- end }}
      restartPolicy: Always
  # Create pvc for dataproxy
  {{- if .Values.dataproxy.volumes.persistence }}
  volumeClaimTemplates:
    - metadata:
        name: {{ template "inlong.fullname" . }}-{{ .Values.dataproxy.component }}-{{ .Values.dataproxy.volumes.name }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.dataproxy.volumes.size }}
        {{- if .Values.dataproxy.volumes.storageClassName }}
        storageClassName: "{{ .Values.dataproxy.volumes.storageClassName }}"
        {{- end }}
  {{- end }}
{{- end }}
